[package]
name = "project_structure"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = ["test_library"]

[workspace.dependencies]
serde = {  version = "1.0.219", features = ["derive"] }
